-- Add missing Hld approval and stale detection fields
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "lastActivityAt" TIMESTAMP(3);
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "staleMarkedAt" TIMESTAMP(3);
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "isStale" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "pmNotes" TEXT;
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "adminNotes" TEXT;
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "pmRejectedAt" TIMESTAMP(3);
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "adminRejectedAt" TIMESTAMP(3);
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "pmApproverName" TEXT;
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "pmApproverRole" TEXT;
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "pmApproverSignatureUrl" TEXT;
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "adminApproverName" TEXT;
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "adminApproverRole" TEXT;
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "adminApproverSignatureUrl" TEXT;
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "pmApprovedBy" TEXT;
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "pmApprovedAt" TIMESTAMP(3);
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "adminApprovedBy" TEXT;
ALTER TABLE "Hld" ADD COLUMN IF NOT EXISTS "adminApprovedAt" TIMESTAMP(3);

-- Add missing Lld approval and stale detection fields
ALTER TABLE "Lld" ADD COLUMN IF NOT EXISTS "lastActivityAt" TIMESTAMP(3);
ALTER TABLE "Lld" ADD COLUMN IF NOT EXISTS "staleMarkedAt" TIMESTAMP(3);
ALTER TABLE "Lld" ADD COLUMN IF NOT EXISTS "isStale" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Lld" ADD COLUMN IF NOT EXISTS "adminNotes" TEXT;
ALTER TABLE "Lld" ADD COLUMN IF NOT EXISTS "pmApproverName" TEXT;
ALTER TABLE "Lld" ADD COLUMN IF NOT EXISTS "pmApproverRole" TEXT;
ALTER TABLE "Lld" ADD COLUMN IF NOT EXISTS "pmApproverSignatureUrl" TEXT;
ALTER TABLE "Lld" ADD COLUMN IF NOT EXISTS "adminApproverName" TEXT;
ALTER TABLE "Lld" ADD COLUMN IF NOT EXISTS "adminApproverRole" TEXT;
ALTER TABLE "Lld" ADD COLUMN IF NOT EXISTS "adminApproverSignatureUrl" TEXT;
ALTER TABLE "Lld" ADD COLUMN IF NOT EXISTS "pmApprovedBy" TEXT;
ALTER TABLE "Lld" ADD COLUMN IF NOT EXISTS "pmApprovedAt" TIMESTAMP(3);
ALTER TABLE "Lld" ADD COLUMN IF NOT EXISTS "adminApprovedBy" TEXT;
ALTER TABLE "Lld" ADD COLUMN IF NOT EXISTS "adminApprovedAt" TIMESTAMP(3);

-- Add foreign keys for approval fields
ALTER TABLE "Hld" ADD CONSTRAINT "Hld_pmApprovedBy_fkey" FOREIGN KEY ("pmApprovedBy") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Hld" ADD CONSTRAINT "Hld_adminApprovedBy_fkey" FOREIGN KEY ("adminApprovedBy") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Lld" ADD CONSTRAINT "Lld_pmApprovedBy_fkey" FOREIGN KEY ("pmApprovedBy") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
ALTER TABLE "Lld" ADD CONSTRAINT "Lld_adminApprovedBy_fkey" FOREIGN KEY ("adminApprovedBy") REFERENCES "User"("id") ON DELETE SET NULL ON UPDATE CASCADE;
